### ISSUE TITLE
Script crashing with TypeError: this.ws.on is not a function

### ISSUE THREAD

**Issue by BlueManCZ** [brucejcooper/roon-mpris#2]
Recently the script started crashing immediately with the following TypeError:
```
» roon-mpris
Autodiscovery of Core
asking for position

/usr/lib64/node_modules/roon-mpris/node_modules/node-roon-api/transport-websocket.js:17
    this.ws.on('pong', () => this.is_alive = true);
            ^
TypeError: this.ws.on is not a function
    at new Transport (/usr/lib64/node_modules/roon-mpris/node_modules/node-roon-api/transport-websocket.js:17:13)
    at RoonApi.ws_connect (/usr/lib64/node_modules/roon-mpris/node_modules/node-roon-api/lib.js:397:23)
    at Sood.<anonymous> (/usr/lib64/node_modules/roon-mpris/node_modules/node-roon-api/lib.js:143:66)
    at Sood.emit (node:events:520:28)
    at Socket.<anonymous> (/usr/lib64/node_modules/roon-mpris/node_modules/node-roon-api/sood.js:149:27)
    at Socket.emit (node:events:520:28)
    at UDP.onMessage (node:dgram:944:8)
```

**Comment by BlueManCZ** [comment]
This is reported issue in https://github.com/RoonLabs/node-roon-api/issues/37
